// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTAWgy3eLRaadxC01iC4vBkdBaD4ieaYY',
    appId: '1:726033794549:web:c5dc0e0db1c6e7e0344cbc',
    messagingSenderId: '726033794549',
    projectId: 'todoapp-17337',
    authDomain: 'todoapp-17337.firebaseapp.com',
    storageBucket: 'todoapp-17337.appspot.com',
    measurementId: 'G-K60K61YKTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6gOEfGPzmWu6PAx4pDMBcbTz9N8wBKo',
    appId: '1:726033794549:android:ee2ff6ac6f525602344cbc',
    messagingSenderId: '726033794549',
    projectId: 'todoapp-17337',
    storageBucket: 'todoapp-17337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWg_XbTi8ufw6q7gPSxGefv7YTjMLe2U',
    appId: '1:726033794549:ios:99fc8d4eca58231f344cbc',
    messagingSenderId: '726033794549',
    projectId: 'todoapp-17337',
    storageBucket: 'todoapp-17337.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLWg_XbTi8ufw6q7gPSxGefv7YTjMLe2U',
    appId: '1:726033794549:ios:fdc7687b0c56c408344cbc',
    messagingSenderId: '726033794549',
    projectId: 'todoapp-17337',
    storageBucket: 'todoapp-17337.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
